kafka:
  producer:
    configuration:
      bootstrap.servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka_client.AvroSerializer
  topics:
    sensors-events: telemetry.sensors.v1
    hubs-events: telemetry.hubs.v1